### ISSUE TITLE
unkown website youtube

### ISSUE THREAD

**Issue by decadenceqi** [Media-Fetch-Pro/Media-Fetch-Pro#6]
https://www.youtube.com/watch?app=desktop&v=tbl9jxvlVgA

**Comment by CorrectRoadH** [comment]
thanks for your feedback. I will try to fix it.

**Comment by CorrectRoadH** [comment]
🤣The bug is hard to fix right now. Because the architecture is awful. So you can use `https://www.youtube.com/watch?v=tbl9jxvlVgA` to download the video.
